//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tamsa.View.ProductionReport.View.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tamsa.View.ProductionReport.View.Resources.ApplicationResources", typeof(ApplicationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string AcceptButton {
            get {
                return ResourceManager.GetString("AcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit Application Module.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Basket.
        /// </summary>
        public static string Basket {
            get {
                return ResourceManager.GetString("Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Basket Number.
        /// </summary>
        public static string BasketNumber {
            get {
                return ResourceManager.GetString("BasketNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close Bundle.
        /// </summary>
        public static string CloseTrackingGroupButton {
            get {
                return ResourceManager.GetString("CloseTrackingGroupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compliance Graph.
        /// </summary>
        public static string ComplianceGraphTitle {
            get {
                return ResourceManager.GetString("ComplianceGraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        public static string ConfirmButton {
            get {
                return ResourceManager.GetString("ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy Numbers.
        /// </summary>
        public static string CopyNumber {
            get {
                return ResourceManager.GetString("CopyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Bundle.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Piece.
        /// </summary>
        public static string DeleteTrackingButton {
            get {
                return ResourceManager.GetString("DeleteTrackingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destiny Bundle.
        /// </summary>
        public static string DestinyTrackingGroup {
            get {
                return ResourceManager.GetString("DestinyTrackingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Bundle.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Bundle.
        /// </summary>
        public static string EditTrackingGroupTitle {
            get {
                return ResourceManager.GetString("EditTrackingGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elaboration State.
        /// </summary>
        public static string ElaborationState {
            get {
                return ResourceManager.GetString("ElaborationState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exceeded.
        /// </summary>
        public static string Exceeded {
            get {
                return ResourceManager.GetString("Exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit Management.
        /// </summary>
        public static string ExitManagementTab {
            get {
                return ResourceManager.GetString("ExitManagementTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit Status.
        /// </summary>
        public static string ExitStatusTab {
            get {
                return ResourceManager.GetString("ExitStatusTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finish.
        /// </summary>
        public static string FinishButton {
            get {
                return ResourceManager.GetString("FinishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historic.
        /// </summary>
        public static string HistoricTab {
            get {
                return ResourceManager.GetString("HistoricTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In Process.
        /// </summary>
        public static string InProcess {
            get {
                return ResourceManager.GetString("InProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Bundle.
        /// </summary>
        public static string InsertButton {
            get {
                return ResourceManager.GetString("InsertButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Piece.
        /// </summary>
        public static string InsertTrackingButton {
            get {
                return ResourceManager.GetString("InsertTrackingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Bundle.
        /// </summary>
        public static string InsertTrackingGroupTitle {
            get {
                return ResourceManager.GetString("InsertTrackingGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Bundle.
        /// </summary>
        public static string InsertTrackingTitle {
            get {
                return ResourceManager.GetString("InsertTrackingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IT Send Status:.
        /// </summary>
        public static string ITSendStatus {
            get {
                return ResourceManager.GetString("ITSendStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string ITSendStatusError {
            get {
                return ResourceManager.GetString("ITSendStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        public static string ITSendStatusOK {
            get {
                return ResourceManager.GetString("ITSendStatusOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pending.
        /// </summary>
        public static string ITSendStatusPending {
            get {
                return ResourceManager.GetString("ITSendStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Length [m].
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loaded.
        /// </summary>
        public static string Loaded {
            get {
                return ResourceManager.GetString("Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loaded Pieces:.
        /// </summary>
        public static string LoadedPiecesTitle {
            get {
                return ResourceManager.GetString("LoadedPiecesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lot Number.
        /// </summary>
        public static string LotNumber {
            get {
                return ResourceManager.GetString("LotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max..
        /// </summary>
        public static string Maximum {
            get {
                return ResourceManager.GetString("Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum.
        /// </summary>
        public static string MaximumToLoad {
            get {
                return ResourceManager.GetString("MaximumToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure of to close the selected bundle?.
        /// </summary>
        public static string MessageCloseTrackingGroup {
            get {
                return ResourceManager.GetString("MessageCloseTrackingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure of to delete the selected pieces?.
        /// </summary>
        public static string MessageDeleteTracking {
            get {
                return ResourceManager.GetString("MessageDeleteTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure of to delete the selected bundles?.
        /// </summary>
        public static string MessageDeleteTrackingGroup {
            get {
                return ResourceManager.GetString("MessageDeleteTrackingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡You must to select a basket!.
        /// </summary>
        public static string MessageSelectedZone {
            get {
                return ResourceManager.GetString("MessageSelectedZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡The amount pieces is major that the loaded pieces!.
        /// </summary>
        public static string MessageWarningExceededPieces {
            get {
                return ResourceManager.GetString("MessageWarningExceededPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a !A field is emply!.
        /// </summary>
        public static string MessageWarningMissingField {
            get {
                return ResourceManager.GetString("MessageWarningMissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Non exits a product in process!.
        /// </summary>
        public static string MessageWarningNonExistProduct {
            get {
                return ResourceManager.GetString("MessageWarningNonExistProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Not exist selected pieces!.
        /// </summary>
        public static string MessageWarningSelectedTracking {
            get {
                return ResourceManager.GetString("MessageWarningSelectedTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡You must to select only one register for this operation!.
        /// </summary>
        public static string MessageWarningSelectedTrackingGroup {
            get {
                return ResourceManager.GetString("MessageWarningSelectedTrackingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡You can not to select the  bundle in process!.
        /// </summary>
        public static string MessageWarningSelectedTrackingGroupInProcess {
            get {
                return ResourceManager.GetString("MessageWarningSelectedTrackingGroupInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡You can not to select the  bundle in status pending!.
        /// </summary>
        public static string MessageWarningSelectedTrackingGroupPending {
            get {
                return ResourceManager.GetString("MessageWarningSelectedTrackingGroupPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡You must to select a specific zone for execute this operation!.
        /// </summary>
        public static string MessageWarningSelectedZone {
            get {
                return ResourceManager.GetString("MessageWarningSelectedZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡The bundle is not sent to IT!.
        /// </summary>
        public static string MessageWarningTrackingGroupNonSent {
            get {
                return ResourceManager.GetString("MessageWarningTrackingGroupNonSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡The bundle was sent to IT and the tracking number exits!.
        /// </summary>
        public static string MessageWarningTrackingGroupSent {
            get {
                return ResourceManager.GetString("MessageWarningTrackingGroupSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Move Pieces.
        /// </summary>
        public static string MoveTrackingButton {
            get {
                return ResourceManager.GetString("MoveTrackingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Move Pieces.
        /// </summary>
        public static string MoveTrackingTitle {
            get {
                return ResourceManager.GetString("MoveTrackingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Non Assing Pieces.
        /// </summary>
        public static string NonAssingPieces {
            get {
                return ResourceManager.GetString("NonAssingPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pending Pieces.
        /// </summary>
        public static string PendingPieces {
            get {
                return ResourceManager.GetString("PendingPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pieces.
        /// </summary>
        public static string Pieces {
            get {
                return ResourceManager.GetString("Pieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Print Bundle.
        /// </summary>
        public static string PrintButton {
            get {
                return ResourceManager.GetString("PrintButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disabled.
        /// </summary>
        public static string PrinterDisabled {
            get {
                return ResourceManager.GetString("PrinterDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable.
        /// </summary>
        public static string PrinterEnabled {
            get {
                return ResourceManager.GetString("PrinterEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Printer Name.
        /// </summary>
        public static string PrinterName {
            get {
                return ResourceManager.GetString("PrinterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        public static string PrinterStatus {
            get {
                return ResourceManager.GetString("PrinterStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Printer.
        /// </summary>
        public static string PrinterTitle {
            get {
                return ResourceManager.GetString("PrinterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Print Bundle.
        /// </summary>
        public static string PrintTrackingGroupTitle {
            get {
                return ResourceManager.GetString("PrintTrackingGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceced Pieces:.
        /// </summary>
        public static string ProducedPiecesTitle {
            get {
                return ResourceManager.GetString("ProducedPiecesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product Information.
        /// </summary>
        public static string ProductInformationTitle {
            get {
                return ResourceManager.GetString("ProductInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Production Date.
        /// </summary>
        public static string ProductionDate {
            get {
                return ResourceManager.GetString("ProductionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Samples Cut.
        /// </summary>
        public static string ProductionTrackingsGroup {
            get {
                return ResourceManager.GetString("ProductionTrackingsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products Information By Shift.
        /// </summary>
        public static string ProductsInformationTitle {
            get {
                return ResourceManager.GetString("ProductsInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product Status:.
        /// </summary>
        public static string ProductStatus {
            get {
                return ResourceManager.GetString("ProductStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finished.
        /// </summary>
        public static string ProductStatusFinished {
            get {
                return ResourceManager.GetString("ProductStatusFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In Process.
        /// </summary>
        public static string ProductStatusInProcess {
            get {
                return ResourceManager.GetString("ProductStatusInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pending.
        /// </summary>
        public static string ProductStatusPending {
            get {
                return ResourceManager.GetString("ProductStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programmed Pieces:.
        /// </summary>
        public static string ProgrammedPiecesTitle {
            get {
                return ResourceManager.GetString("ProgrammedPiecesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rejection Code.
        /// </summary>
        public static string RejectionCode {
            get {
                return ResourceManager.GetString("RejectionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reject.
        /// </summary>
        public static string RejectProduct {
            get {
                return ResourceManager.GetString("RejectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reworked Bundles.
        /// </summary>
        public static string ReworkedTrackingsGroup {
            get {
                return ResourceManager.GetString("ReworkedTrackingsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rework.
        /// </summary>
        public static string ReworkProduct {
            get {
                return ResourceManager.GetString("ReworkProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scrap.
        /// </summary>
        public static string ScrapProduct {
            get {
                return ResourceManager.GetString("ScrapProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select by capacity bundle.
        /// </summary>
        public static string SelectByTrackingGroup {
            get {
                return ResourceManager.GetString("SelectByTrackingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selected Pieces.
        /// </summary>
        public static string SelectedTracking {
            get {
                return ResourceManager.GetString("SelectedTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Bundle.
        /// </summary>
        public static string SendButton {
            get {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string SendProductButton {
            get {
                return ResourceManager.GetString("SendProductButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Bundle.
        /// </summary>
        public static string SendTrackingGroupTitle {
            get {
                return ResourceManager.GetString("SendTrackingGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shift.
        /// </summary>
        public static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Source Bundle.
        /// </summary>
        public static string SourceTrackingGroup {
            get {
                return ResourceManager.GetString("SourceTrackingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Specific.
        /// </summary>
        public static string Specific {
            get {
                return ResourceManager.GetString("Specific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Traceability Type.
        /// </summary>
        public static string Traceability {
            get {
                return ResourceManager.GetString("Traceability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bundle.
        /// </summary>
        public static string TrackingGroup {
            get {
                return ResourceManager.GetString("TrackingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bundle Details.
        /// </summary>
        public static string TrackingGroupDetail {
            get {
                return ResourceManager.GetString("TrackingGroupDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bundle Status:.
        /// </summary>
        public static string TrackingGroupStatus {
            get {
                return ResourceManager.GetString("TrackingGroupStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error IT Send.
        /// </summary>
        public static string TrackingGroupStatusITSendError {
            get {
                return ResourceManager.GetString("TrackingGroupStatusITSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK IT Send.
        /// </summary>
        public static string TrackingGroupStatusITSendOK {
            get {
                return ResourceManager.GetString("TrackingGroupStatusITSendOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pending IT Send.
        /// </summary>
        public static string TrackingGroupStatusITSendPending {
            get {
                return ResourceManager.GetString("TrackingGroupStatusITSendPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tracking ID.
        /// </summary>
        public static string TrackingID {
            get {
                return ResourceManager.GetString("TrackingID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Piece Number.
        /// </summary>
        public static string TrackingNumber {
            get {
                return ResourceManager.GetString("TrackingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pieces Details.
        /// </summary>
        public static string TrackingsDetail {
            get {
                return ResourceManager.GetString("TrackingsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        public static string TrackingStatus {
            get {
                return ResourceManager.GetString("TrackingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weight [ton].
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
