//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tamsa.View.ProductionReport.View.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CenterResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CenterResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tamsa.View.ProductionReport.View.Resources.CenterResources", typeof(CenterResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Available Pieces.
        /// </summary>
        public static string AvailablePieces {
            get {
                return ResourceManager.GetString("AvailablePieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Justification by exceeded weight.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creation Date.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diameter [mm].
        /// </summary>
        public static string Diameter {
            get {
                return ResourceManager.GetString("Diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elaboration State.
        /// </summary>
        public static string ElaborationState {
            get {
                return ResourceManager.GetString("ElaborationState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Heat.
        /// </summary>
        public static string HeatNumber {
            get {
                return ResourceManager.GetString("HeatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Heat Treatment Number.
        /// </summary>
        public static string HeatTreatmentNumber {
            get {
                return ResourceManager.GetString("HeatTreatmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IT Send Status.
        /// </summary>
        public static string ITStatus {
            get {
                return ResourceManager.GetString("ITStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Length [m].
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loaded Pieces.
        /// </summary>
        public static string LoadedPieces {
            get {
                return ResourceManager.GetString("LoadedPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loaded Weight [ton].
        /// </summary>
        public static string LoadedWeight {
            get {
                return ResourceManager.GetString("LoadedWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max. Pieces.
        /// </summary>
        public static string MaxPieces {
            get {
                return ResourceManager.GetString("MaxPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max. Weight [ton].
        /// </summary>
        public static string MaxWeight {
            get {
                return ResourceManager.GetString("MaxWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pipe Type.
        /// </summary>
        public static string PipeType {
            get {
                return ResourceManager.GetString("PipeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceced Pieces.
        /// </summary>
        public static string ProducedPieces {
            get {
                return ResourceManager.GetString("ProducedPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programmed Pieces.
        /// </summary>
        public static string ProgrammedPieces {
            get {
                return ResourceManager.GetString("ProgrammedPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shift.
        /// </summary>
        public static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steel Code.
        /// </summary>
        public static string SteelCode {
            get {
                return ResourceManager.GetString("SteelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steel Grade.
        /// </summary>
        public static string SteelGrade {
            get {
                return ResourceManager.GetString("SteelGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a StencilColor.
        /// </summary>
        public static string StencilColor {
            get {
                return ResourceManager.GetString("StencilColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thickness [mm].
        /// </summary>
        public static string Thickness {
            get {
                return ResourceManager.GetString("Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bundle .
        /// </summary>
        public static string TrackingGroupID {
            get {
                return ResourceManager.GetString("TrackingGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bundle Number.
        /// </summary>
        public static string TrackingGroupNumber {
            get {
                return ResourceManager.GetString("TrackingGroupNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bundle Status.
        /// </summary>
        public static string TrackingGroupStatus {
            get {
                return ResourceManager.GetString("TrackingGroupStatus", resourceCulture);
            }
        }
    }
}
